name: EXE Oluşturucu
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller windnd
        
    - name: EXE Oluştur
      run: |
        pyinstaller --onefile --noconsole catia_bulucu.py
        
    - name: Dosyayı Paylaş
      uses: actions/upload-artifact@v4
      with:
        name: CatiaProgrami
        path: dist/*.exe
